# Generated by Django 5.2.4 on 2025-08-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
