# Generated by Django 4.2.23 on 2025-07-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="passwrord",
            new_name="password",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_varified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="userName",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
