# Generated by Django 5.2.4 on 2025-08-01 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.BigIntegerField(blank=True, default="3383274"),
        ),
    ]
